[package]
name = "emotion_metadata"
version = "1.0.0"

[addresses]
emotion_metadata = "_"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

